<?php
return array (
  'miaoparty2' => 
  array (
    'status' => '1',
    'from' => 'miaoparty2',
    'show' => '蓝光急速',
    'des' => '百淘影视独家接口',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.58g8.com/?url=',
    'sort' => '99999',
    'tip' => '百淘影视独家接口',
    'id' => 'miaoparty2',
  ),
  'miaoparty' => 
  array (
    'status' => '1',
    'from' => 'miaoparty',
    'show' => '独家蓝光',
    'des' => '百淘影视独家接口',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.58g8.com/?url=',
    'sort' => '99998',
    'tip' => '百淘影视独家接口',
    'id' => 'miaoparty',
  ),
  'miaoparty3' => 
  array (
    'status' => '1',
    'from' => 'miaoparty3',
    'show' => '蓝光备用',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.58g8.com/?url=',
    'sort' => '99997',
    'tip' => '',
    'id' => 'miaoparty3',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '奇异视频',
    'des' => 'www.iqiyi.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.58g8.com/?url=',
    'sort' => '9899',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷视频',
    'des' => 'www.youku.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.58g8.com/?url=',
    'sort' => '9799',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果视频',
    'des' => 'www.mgtv.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.58g8.com/?url=',
    'sort' => '9699',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐视频',
    'des' => 'tv.sohu.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.58g8.com/?url=',
    'sort' => '9599',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'm1905' => 
  array (
    'status' => '1',
    'from' => 'm1905',
    'show' => 'm1905',
    'des' => 'www.m1905.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.58g8.com/?url=',
    'sort' => '9299',
    'tip' => '无需安装任何插件',
    'id' => 'm1905',
  ),
  'bilibili' => 
  array (
    'status' => '1',
    'from' => 'bilibili',
    'show' => 'bilibili',
    'des' => 'www.bilibili.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.nxflv.com/?url=',
    'sort' => '8799',
    'tip' => '无需安装任何插件',
    'id' => 'bilibili',
  ),
  'wolong' => 
  array (
    'status' => '1',
    'from' => 'wolong',
    'show' => 'wolong',
    'des' => '卧龙资源',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.wolongzywcdn.com:65/m3u8.php?url=',
    'sort' => '1000',
    'tip' => '',
    'id' => 'wolong',
  ),
  'fsm3u8' => 
  array (
    'status' => '1',
    'from' => 'fsm3u8',
    'show' => '飞速m3u8',
    'des' => '在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.feisuplayer.com/m3u8/?url=',
    'sort' => '998',
    'tip' => '',
    'id' => 'fsm3u8',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯视频',
    'des' => 'v.qq.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.58g8.com/?url=',
    'sort' => '99',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'sdm3u8' => 
  array (
    'status' => '1',
    'from' => 'sdm3u8',
    'show' => '闪电在线',
    'des' => '闪电在线',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.shankubf.com/m3u8/?url=',
    'sort' => '99',
    'tip' => '闪电在线',
    'id' => 'sdm3u8',
  ),
  'ukm3u8' => 
  array (
    'status' => '1',
    'from' => 'ukm3u8',
    'show' => 'ukm3u8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://api.ukubf.com/m3u8/?url=',
    'sort' => '99',
    'tip' => '',
    'id' => 'ukm3u8',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => 'pptv',
    'des' => 'www.pptv.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://okjx.cc/?url=',
    'sort' => '94',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视视频',
    'des' => 'www.le.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.nxflv.com/?url=',
    'sort' => '93',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
  'wasu' => 
  array (
    'status' => '1',
    'from' => 'wasu',
    'show' => '华数视频',
    'des' => 'www.wasu.cn',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.nxflv.com/?url=',
    'sort' => '91',
    'tip' => '无需安装任何插件',
    'id' => 'wasu',
  ),
  'migu' => 
  array (
    'status' => '1',
    'from' => 'migu',
    'show' => '咪咕视频',
    'des' => 'www.miguvideo.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.nxflv.com/?url=',
    'sort' => '89',
    'tip' => '无需安装任何插件',
    'id' => 'migu',
  ),
  'funshion' => 
  array (
    'status' => '1',
    'from' => 'funshion',
    'show' => '风行视频',
    'des' => 'funshion.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.nxflv.com/?url=',
    'sort' => '88',
    'tip' => '无需安装任何插件',
    'id' => 'funshion',
  ),
  'cctv' => 
  array (
    'status' => '1',
    'from' => 'cctv',
    'show' => 'cctv',
    'des' => 'tv.cctv.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.nxflv.com/?url=',
    'sort' => '86',
    'tip' => '无需安装任何插件',
    'id' => 'cctv',
  ),
  'cntv' => 
  array (
    'status' => '1',
    'from' => 'cntv',
    'show' => 'cntv',
    'des' => 'tv.cctv.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.nxflv.com/?url=',
    'sort' => '85',
    'tip' => '无需安装任何插件',
    'id' => 'cntv',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'link' => 
  array (
    'status' => '1',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'xigua' => 
  array (
    'status' => '1',
    'from' => 'xigua',
    'show' => '西瓜',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'http://api.xdiaosi.com/?url=',
    'sort' => '1',
    'tip' => '',
    'id' => 'xigua',
  ),
);